title: Salvatierra Julian
logo: /assets/img/profile.jpeg
description: " "
show_downloads: false
theme: jekyll-theme-minimal
minima:
  social_links:
    github: jekyll
    linkedin: jekyll
include:
  - style.css
