title: Salvatierra Julian
logo: /assets/img/profile.jpeg
description: " "
show_downloads: true
theme: jekyll-theme-minimal
minima:
  social_links:
    - name: "GitHub"
      url: "https://github.com/Savenast"
    - name: "Linkedin"
      url: "linkedin.com/in/julián-salvatierra-653a04175"

